"""Increase size of username column in User table

Revision ID: a0bf356a1114
Revises: add198635594
Create Date: 2024-08-02 00:16:53.041476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0bf356a1114'
down_revision = 'add198635594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('document_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('docdate')

    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_column('mod_date')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=130),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=70),
               existing_nullable=False)

    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('video_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_date', sa.DATETIME(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=70),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=130),
               type_=sa.VARCHAR(length=60),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mod_date', sa.DATETIME(), nullable=False))

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('docdate', sa.DATE(), nullable=True))
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('document_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
